---
- name: Docker Installation
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      import_role:
        name: geerlingguy.docker
      vars:
        docker_package: "docker-ce-18.09.9"

    - name: Add admin user to docker group
      user:
        name: admin
        group: docker
