---
- name: Master Initialization
  hosts: master
  tasks:
    - name: Initialize the Kubernetes cluster using kubeadm
      become: yes
      command: kubeadm init --pod-network-cidr=172.16.0.0/16 --apiserver-advertise-address=192.168.33.101 --apiserver-cert-extra-sans=192.168.33.101

    - name: Create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/admin/.kube/config
        remote_src: yes
        owner: admin

    - name: Install Pod network
      shell: kubectl apply -f "{{ playbook_dir}}/manifests/calico-v3.10.yaml"
      become: yes
      become_method: sudo
      become_user: admin

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
